window.esdocSearchIndex = [
  [
    "n2n-overlay-wrtc~eventemitter",
    "variable/index.html#static-variable-EventEmitter",
    "<span>EventEmitter</span> <span class=\"search-result-import-path\">n2n-overlay-wrtc</span>",
    "variable"
  ],
  [
    "n2n-overlay-wrtc/lib/messages/mconnectto.js~mconnectto",
    "class/lib/messages/mconnectto.js~MConnectTo.html",
    "<span>MConnectTo</span> <span class=\"search-result-import-path\">n2n-overlay-wrtc/lib/messages/mconnectto.js</span>",
    "class"
  ],
  [
    "n2n-overlay-wrtc/lib/messages/mdirect.js~mdirect",
    "class/lib/messages/mdirect.js~MDirect.html",
    "<span>MDirect</span> <span class=\"search-result-import-path\">n2n-overlay-wrtc/lib/messages/mdirect.js</span>",
    "class"
  ],
  [
    "n2n-overlay-wrtc/lib/messages/mforwardto.js~mforwardto",
    "class/lib/messages/mforwardto.js~MForwardTo.html",
    "<span>MForwardTo</span> <span class=\"search-result-import-path\">n2n-overlay-wrtc/lib/messages/mforwardto.js</span>",
    "class"
  ],
  [
    "n2n-overlay-wrtc/lib/messages/mforwarded.js~mforwarded",
    "class/lib/messages/mforwarded.js~MForwarded.html",
    "<span>MForwarded</span> <span class=\"search-result-import-path\">n2n-overlay-wrtc/lib/messages/mforwarded.js</span>",
    "class"
  ],
  [
    "n2n-overlay-wrtc~neighbor",
    "class/lib/n2n-overlay.js~Neighbor.html",
    "<span>Neighbor</span> <span class=\"search-result-import-path\">n2n-overlay-wrtc</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "https://developer.mozilla.org/en/docs/Web/API/AudioContext",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "https://developer.mozilla.org/en-US/docs/Web/API/Element",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "https://developer.mozilla.org/en-US/docs/Web/API/Event",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "https://developer.mozilla.org/en-US/docs/Web/API/Node",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "https://developer.mozilla.org/en-US/docs/Web/API/NodeList",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "lib/messages/mconnectto.js",
    "file/lib/messages/mconnectto.js.html",
    "lib/messages/mconnectto.js",
    "file"
  ],
  [
    "lib/messages/mconnectto.js~mconnectto#constructor",
    "class/lib/messages/mconnectto.js~MConnectTo.html#instance-constructor-constructor",
    "lib/messages/mconnectto.js~MConnectTo#constructor",
    "method"
  ],
  [
    "lib/messages/mconnectto.js~mconnectto#from",
    "class/lib/messages/mconnectto.js~MConnectTo.html#instance-member-from",
    "lib/messages/mconnectto.js~MConnectTo#from",
    "member"
  ],
  [
    "lib/messages/mconnectto.js~mconnectto#to",
    "class/lib/messages/mconnectto.js~MConnectTo.html#instance-member-to",
    "lib/messages/mconnectto.js~MConnectTo#to",
    "member"
  ],
  [
    "lib/messages/mconnectto.js~mconnectto#type",
    "class/lib/messages/mconnectto.js~MConnectTo.html#instance-member-type",
    "lib/messages/mconnectto.js~MConnectTo#type",
    "member"
  ],
  [
    "lib/messages/mdirect.js",
    "file/lib/messages/mdirect.js.html",
    "lib/messages/mdirect.js",
    "file"
  ],
  [
    "lib/messages/mdirect.js~mdirect#constructor",
    "class/lib/messages/mdirect.js~MDirect.html#instance-constructor-constructor",
    "lib/messages/mdirect.js~MDirect#constructor",
    "method"
  ],
  [
    "lib/messages/mdirect.js~mdirect#type",
    "class/lib/messages/mdirect.js~MDirect.html#instance-member-type",
    "lib/messages/mdirect.js~MDirect#type",
    "member"
  ],
  [
    "lib/messages/mforwarded.js",
    "file/lib/messages/mforwarded.js.html",
    "lib/messages/mforwarded.js",
    "file"
  ],
  [
    "lib/messages/mforwarded.js~mforwarded#constructor",
    "class/lib/messages/mforwarded.js~MForwarded.html#instance-constructor-constructor",
    "lib/messages/mforwarded.js~MForwarded#constructor",
    "method"
  ],
  [
    "lib/messages/mforwarded.js~mforwarded#from",
    "class/lib/messages/mforwarded.js~MForwarded.html#instance-member-from",
    "lib/messages/mforwarded.js~MForwarded#from",
    "member"
  ],
  [
    "lib/messages/mforwarded.js~mforwarded#message",
    "class/lib/messages/mforwarded.js~MForwarded.html#instance-member-message",
    "lib/messages/mforwarded.js~MForwarded#message",
    "member"
  ],
  [
    "lib/messages/mforwarded.js~mforwarded#to",
    "class/lib/messages/mforwarded.js~MForwarded.html#instance-member-to",
    "lib/messages/mforwarded.js~MForwarded#to",
    "member"
  ],
  [
    "lib/messages/mforwarded.js~mforwarded#type",
    "class/lib/messages/mforwarded.js~MForwarded.html#instance-member-type",
    "lib/messages/mforwarded.js~MForwarded#type",
    "member"
  ],
  [
    "lib/messages/mforwardto.js",
    "file/lib/messages/mforwardto.js.html",
    "lib/messages/mforwardto.js",
    "file"
  ],
  [
    "lib/messages/mforwardto.js~mforwardto#constructor",
    "class/lib/messages/mforwardto.js~MForwardTo.html#instance-constructor-constructor",
    "lib/messages/mforwardto.js~MForwardTo#constructor",
    "method"
  ],
  [
    "lib/messages/mforwardto.js~mforwardto#from",
    "class/lib/messages/mforwardto.js~MForwardTo.html#instance-member-from",
    "lib/messages/mforwardto.js~MForwardTo#from",
    "member"
  ],
  [
    "lib/messages/mforwardto.js~mforwardto#message",
    "class/lib/messages/mforwardto.js~MForwardTo.html#instance-member-message",
    "lib/messages/mforwardto.js~MForwardTo#message",
    "member"
  ],
  [
    "lib/messages/mforwardto.js~mforwardto#to",
    "class/lib/messages/mforwardto.js~MForwardTo.html#instance-member-to",
    "lib/messages/mforwardto.js~MForwardTo#to",
    "member"
  ],
  [
    "lib/messages/mforwardto.js~mforwardto#type",
    "class/lib/messages/mforwardto.js~MForwardTo.html#instance-member-type",
    "lib/messages/mforwardto.js~MForwardTo#type",
    "member"
  ],
  [
    "lib/n2n-overlay.js",
    "file/lib/n2n-overlay.js.html",
    "lib/n2n-overlay.js",
    "file"
  ],
  [
    "lib/n2n-overlay.js~neighbor#ii",
    "class/lib/n2n-overlay.js~Neighbor.html#instance-member-II",
    "lib/n2n-overlay.js~Neighbor#II",
    "member"
  ],
  [
    "lib/n2n-overlay.js~neighbor#io",
    "class/lib/n2n-overlay.js~Neighbor.html#instance-member-IO",
    "lib/n2n-overlay.js~Neighbor#IO",
    "member"
  ],
  [
    "lib/n2n-overlay.js~neighbor#ni",
    "class/lib/n2n-overlay.js~Neighbor.html#instance-member-NI",
    "lib/n2n-overlay.js~Neighbor#NI",
    "member"
  ],
  [
    "lib/n2n-overlay.js~neighbor#no",
    "class/lib/n2n-overlay.js~Neighbor.html#instance-member-NO",
    "lib/n2n-overlay.js~Neighbor#NO",
    "member"
  ],
  [
    "lib/n2n-overlay.js~neighbor#peer",
    "class/lib/n2n-overlay.js~Neighbor.html#instance-member-PEER",
    "lib/n2n-overlay.js~Neighbor#PEER",
    "member"
  ],
  [
    "lib/n2n-overlay.js~neighbor#pid",
    "class/lib/n2n-overlay.js~Neighbor.html#instance-member-PID",
    "lib/n2n-overlay.js~Neighbor#PID",
    "member"
  ],
  [
    "lib/n2n-overlay.js~neighbor#connect",
    "class/lib/n2n-overlay.js~Neighbor.html#instance-method-connect",
    "lib/n2n-overlay.js~Neighbor#connect",
    "method"
  ],
  [
    "lib/n2n-overlay.js~neighbor#constructor",
    "class/lib/n2n-overlay.js~Neighbor.html#instance-constructor-constructor",
    "lib/n2n-overlay.js~Neighbor#constructor",
    "method"
  ],
  [
    "lib/n2n-overlay.js~neighbor#disconnect",
    "class/lib/n2n-overlay.js~Neighbor.html#instance-method-disconnect",
    "lib/n2n-overlay.js~Neighbor#disconnect",
    "method"
  ],
  [
    "lib/n2n-overlay.js~neighbor#getinview",
    "class/lib/n2n-overlay.js~Neighbor.html#instance-method-getInview",
    "lib/n2n-overlay.js~Neighbor#getInview",
    "method"
  ],
  [
    "lib/n2n-overlay.js~neighbor#getinviewid",
    "class/lib/n2n-overlay.js~Neighbor.html#instance-method-getInviewId",
    "lib/n2n-overlay.js~Neighbor#getInviewId",
    "method"
  ],
  [
    "lib/n2n-overlay.js~neighbor#getoutview",
    "class/lib/n2n-overlay.js~Neighbor.html#instance-method-getOutview",
    "lib/n2n-overlay.js~Neighbor#getOutview",
    "method"
  ],
  [
    "lib/n2n-overlay.js~neighbor#getoutviewid",
    "class/lib/n2n-overlay.js~Neighbor.html#instance-method-getOutviewId",
    "lib/n2n-overlay.js~Neighbor#getOutviewId",
    "method"
  ],
  [
    "lib/n2n-overlay.js~neighbor#i",
    "class/lib/n2n-overlay.js~Neighbor.html#instance-member-i",
    "lib/n2n-overlay.js~Neighbor#i",
    "member"
  ],
  [
    "lib/n2n-overlay.js~neighbor#o",
    "class/lib/n2n-overlay.js~Neighbor.html#instance-member-o",
    "lib/n2n-overlay.js~Neighbor#o",
    "member"
  ],
  [
    "lib/n2n-overlay.js~neighbor#options",
    "class/lib/n2n-overlay.js~Neighbor.html#instance-member-options",
    "lib/n2n-overlay.js~Neighbor#options",
    "member"
  ],
  [
    "lib/n2n-overlay.js~neighbor#send",
    "class/lib/n2n-overlay.js~Neighbor.html#instance-method-send",
    "lib/n2n-overlay.js~Neighbor#send",
    "method"
  ]
]